version: '2'
services:
    deitel-image:
        image: deitel:alpine
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - gid
                - uid
