version: '2'
services:
    deitel-image:
        image: deitel
        build:
            context: ..
            dockerfile: Dockerfile
            args:
                - uid
                - gid
        command: echo 
    devel:
        image: deitel
        command: sh
        working_dir: /opt/source/Chapter_9
        volumes:
            - ..:/opt/source
        depends_on:
            - deitel-image
    debug:
        image: deitel
        command: make __debug gcov
        working_dir: /opt/source/Chapter_9
        volumes:
            - ..:/opt/source
    release:
        image: deitel
        command: make __release gcov
        working_dir: /opt/source/Chapter_9
        volumes:
            - ..:/opt/source