version: '2'

services:
    deitel-image:
        image: deitel
        build:
            context: ..
            dockerfile: Dockerfile
            args:
                - uid
                - gid
        command: echo
    devel:
        image: deitel
        command: sh
        working_dir: /opt/source/Chapter_9
        volumes:
            - ..:/opt/source
        depends_on:
            - deitel-image
    debug:
        image: deitel
        command: ls -l
        working_dir: /jenkins
        volumes:
            - jenkins-data:/jenkins
    release:
        image: deitel
        command: make __release gcov
        working_dir: /opt/source/Chapter_9
        volumes:
            - ..:/opt/source
    jenkins-server:
        image: jenkins-image
        build:
            context: .
            dockerfile: Dockerfile.jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home
            - //var/run/docker.sock:/var/run/docker.sock

volumes:
    jenkins-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /c/Users/mtrda/.jenkins