version : '3.7'

services:
    jenkins-server:
        image: jenkins-image
        container_name: jenkins-server
        build:
            context: .
            dockerfile: Dockerfile.jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home
            - //var/run/docker.sock:/var/run/docker.sock

volumes:
    jenkins-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /c/Users/mtrda/.jenkins